import Navbar from "@/components/root-layout/navbar/navbar/navbar";
import type { Metadata } from "next";
import "./globals.css";
import { featureDisplay, neueMontreal } from "@/assets/fonts";

export const metadata: Metadata = {
  title: "AI BOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${neueMontreal.variable} ${featureDisplay.variable}`}
    >
      <body className="">
        <Navbar />
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
